#ifndef ZHINENGTIKACORE_GLOBAL_H
#define ZHINENGTIKACORE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ZHINENGTIKACORE_LIBRARY)
#  define ZHINENGTIKACORE_EXPORT Q_DECL_EXPORT
#else
#  define ZHINENGTIKACORE_EXPORT Q_DECL_IMPORT
#endif

#endif // ZHINENGTIKACORE_GLOBAL_H
