Qt += core gui multimedia

TARGET = zxing

TEMPLATE = lib
CONFIG += staticlib

DEFINES += ZXING_READERS

INCLUDEPATH += $$PWD/src/zxing-cpp

HEADERS += \
    $$PWD/../3rd/zxing-cpp/core/src/Barcode.h \
    $$PWD/../3rd/zxing-cpp/core/src/BarcodeFormat.h \
    $$PWD/../3rd/zxing-cpp/core/src/BinaryBitmap.h \
    $$PWD/../3rd/zxing-cpp/core/src/BitArray.h \
    $$PWD/../3rd/zxing-cpp/core/src/BitHacks.h \
    $$PWD/../3rd/zxing-cpp/core/src/BitMatrix.h \
    $$PWD/../3rd/zxing-cpp/core/src/BitMatrixCursor.h \
    $$PWD/../3rd/zxing-cpp/core/src/BitMatrixIO.h \
    $$PWD/../3rd/zxing-cpp/core/src/BitSource.h \
    $$PWD/../3rd/zxing-cpp/core/src/ByteArray.h \
    $$PWD/../3rd/zxing-cpp/core/src/ByteMatrix.h \
    $$PWD/../3rd/zxing-cpp/core/src/CharacterSet.h \
    $$PWD/../3rd/zxing-cpp/core/src/ConcentricFinder.h \
    $$PWD/../3rd/zxing-cpp/core/src/Content.h \
    $$PWD/../3rd/zxing-cpp/core/src/DecodeHints.h \
    $$PWD/../3rd/zxing-cpp/core/src/DecoderResult.h \
    $$PWD/../3rd/zxing-cpp/core/src/DetectorResult.h \
    $$PWD/../3rd/zxing-cpp/core/src/ECI.h \
    $$PWD/../3rd/zxing-cpp/core/src/Error.h \
    $$PWD/../3rd/zxing-cpp/core/src/Flags.h \
    $$PWD/../3rd/zxing-cpp/core/src/GTIN.h \
    $$PWD/../3rd/zxing-cpp/core/src/Generator.h \
    $$PWD/../3rd/zxing-cpp/core/src/GenericGF.h \
    $$PWD/../3rd/zxing-cpp/core/src/GenericGFPoly.h \
    $$PWD/../3rd/zxing-cpp/core/src/GlobalHistogramBinarizer.h \
    $$PWD/../3rd/zxing-cpp/core/src/GridSampler.h \
    $$PWD/../3rd/zxing-cpp/core/src/HRI.h \
    $$PWD/../3rd/zxing-cpp/core/src/HybridBinarizer.h \
    $$PWD/../3rd/zxing-cpp/core/src/ImageView.h \
    $$PWD/../3rd/zxing-cpp/core/src/LogMatrix.h \
    $$PWD/../3rd/zxing-cpp/core/src/Matrix.h \
    $$PWD/../3rd/zxing-cpp/core/src/MultiFormatReader.h \
    $$PWD/../3rd/zxing-cpp/core/src/MultiFormatWriter.h \
    $$PWD/../3rd/zxing-cpp/core/src/Pattern.h \
    $$PWD/../3rd/zxing-cpp/core/src/PerspectiveTransform.h \
    $$PWD/../3rd/zxing-cpp/core/src/Point.h \
    $$PWD/../3rd/zxing-cpp/core/src/Quadrilateral.h \
    $$PWD/../3rd/zxing-cpp/core/src/Range.h \
    $$PWD/../3rd/zxing-cpp/core/src/ReadBarcode.h \
    $$PWD/../3rd/zxing-cpp/core/src/Reader.h \
    $$PWD/../3rd/zxing-cpp/core/src/ReaderOptions.h \
    $$PWD/../3rd/zxing-cpp/core/src/ReedSolomonDecoder.h \
    $$PWD/../3rd/zxing-cpp/core/src/ReedSolomonEncoder.h \
    $$PWD/../3rd/zxing-cpp/core/src/RegressionLine.h \
    $$PWD/../3rd/zxing-cpp/core/src/Result.h \
    $$PWD/../3rd/zxing-cpp/core/src/ResultPoint.h \
    $$PWD/../3rd/zxing-cpp/core/src/Scope.h \
    $$PWD/../3rd/zxing-cpp/core/src/StructuredAppend.h \
    $$PWD/../3rd/zxing-cpp/core/src/TextDecoder.h \
    $$PWD/../3rd/zxing-cpp/core/src/TextEncoder.h \
    $$PWD/../3rd/zxing-cpp/core/src/TextUtfEncoding.h \
    $$PWD/../3rd/zxing-cpp/core/src/ThresholdBinarizer.h \
    $$PWD/../3rd/zxing-cpp/core/src/TritMatrix.h \
    $$PWD/../3rd/zxing-cpp/core/src/Utf.h \
    $$PWD/../3rd/zxing-cpp/core/src/WhiteRectDetector.h \
    $$PWD/../3rd/zxing-cpp/core/src/WriteBarcode.h \
    $$PWD/../3rd/zxing-cpp/core/src/ZXAlgorithms.h \
    $$PWD/../3rd/zxing-cpp/core/src/ZXConfig.h \
    $$PWD/../3rd/zxing-cpp/core/src/ZXTestSupport.h \
    $$PWD/../3rd/zxing-cpp/core/src/ZXVersion.h \
    $$PWD/../3rd/zxing-cpp/core/src/ZXingC.h \
    $$PWD/../3rd/zxing-cpp/core/src/ZXingCpp.h \
    $$PWD/../3rd/zxing-cpp/core/src/qrcode/QRBitMatrixParser.h \
    $$PWD/../3rd/zxing-cpp/core/src/qrcode/QRCodecMode.h \
    $$PWD/../3rd/zxing-cpp/core/src/qrcode/QRDataBlock.h \
    $$PWD/../3rd/zxing-cpp/core/src/qrcode/QRDataMask.h \
    $$PWD/../3rd/zxing-cpp/core/src/qrcode/QRDecoder.h \
    $$PWD/../3rd/zxing-cpp/core/src/qrcode/QRDetector.h \
    $$PWD/../3rd/zxing-cpp/core/src/qrcode/QRECB.h \
    $$PWD/../3rd/zxing-cpp/core/src/qrcode/QREncodeResult.h \
    $$PWD/../3rd/zxing-cpp/core/src/qrcode/QREncoder.h \
    $$PWD/../3rd/zxing-cpp/core/src/qrcode/QRErrorCorrectionLevel.h \
    $$PWD/../3rd/zxing-cpp/core/src/qrcode/QRFormatInformation.h \
    $$PWD/../3rd/zxing-cpp/core/src/qrcode/QRMaskUtil.h \
    $$PWD/../3rd/zxing-cpp/core/src/qrcode/QRMatrixUtil.h \
    $$PWD/../3rd/zxing-cpp/core/src/qrcode/QRReader.h \
    $$PWD/../3rd/zxing-cpp/core/src/qrcode/QRVersion.h \
    $$PWD/../3rd/zxing-cpp/core/src/qrcode/QRWriter.h \
    $$PWD/../3rd/zxing-cpp/core/src/aztec/AZDecoder.h \
    $$PWD/../3rd/zxing-cpp/core/src/aztec/AZDetector.h \
    $$PWD/../3rd/zxing-cpp/core/src/aztec/AZDetectorResult.h \
    $$PWD/../3rd/zxing-cpp/core/src/aztec/AZEncoder.h \
    $$PWD/../3rd/zxing-cpp/core/src/aztec/AZEncodingState.h \
    $$PWD/../3rd/zxing-cpp/core/src/aztec/AZHighLevelEncoder.h \
    $$PWD/../3rd/zxing-cpp/core/src/aztec/AZReader.h \
    $$PWD/../3rd/zxing-cpp/core/src/aztec/AZToken.h \
    $$PWD/../3rd/zxing-cpp/core/src/aztec/AZWriter.h \
    $$PWD/../3rd/zxing-cpp/core/src/datamatrix/DMBitLayout.h \
    $$PWD/../3rd/zxing-cpp/core/src/datamatrix/DMDataBlock.h \
    $$PWD/../3rd/zxing-cpp/core/src/datamatrix/DMDecoder.h \
    $$PWD/../3rd/zxing-cpp/core/src/datamatrix/DMDetector.h \
    $$PWD/../3rd/zxing-cpp/core/src/datamatrix/DMECEncoder.h \
    $$PWD/../3rd/zxing-cpp/core/src/datamatrix/DMEncoderContext.h \
    $$PWD/../3rd/zxing-cpp/core/src/datamatrix/DMHighLevelEncoder.h \
    $$PWD/../3rd/zxing-cpp/core/src/datamatrix/DMReader.h \
    $$PWD/../3rd/zxing-cpp/core/src/datamatrix/DMSymbolInfo.h \
    $$PWD/../3rd/zxing-cpp/core/src/datamatrix/DMSymbolShape.h \
    $$PWD/../3rd/zxing-cpp/core/src/datamatrix/DMVersion.h \
    $$PWD/../3rd/zxing-cpp/core/src/datamatrix/DMWriter.h \
    $$PWD/../3rd/zxing-cpp/core/src/libzueci/zueci.h \
    $$PWD/../3rd/zxing-cpp/core/src/libzueci/zueci_big5.h \
    $$PWD/../3rd/zxing-cpp/core/src/libzueci/zueci_common.h \
    $$PWD/../3rd/zxing-cpp/core/src/libzueci/zueci_gb18030.h \
    $$PWD/../3rd/zxing-cpp/core/src/libzueci/zueci_gb2312.h \
    $$PWD/../3rd/zxing-cpp/core/src/libzueci/zueci_gbk.h \
    $$PWD/../3rd/zxing-cpp/core/src/libzueci/zueci_ksx1001.h \
    $$PWD/../3rd/zxing-cpp/core/src/libzueci/zueci_sb.h \
    $$PWD/../3rd/zxing-cpp/core/src/libzueci/zueci_sjis.h \
    $$PWD/../3rd/zxing-cpp/core/src/maxicode/MCBitMatrixParser.h \
    $$PWD/../3rd/zxing-cpp/core/src/maxicode/MCDecoder.h \
    $$PWD/../3rd/zxing-cpp/core/src/maxicode/MCReader.h \
    $$PWD/../3rd/zxing-cpp/core/src/oned/ODCodabarReader.h \
    $$PWD/../3rd/zxing-cpp/core/src/oned/ODCodabarWriter.h \
    $$PWD/../3rd/zxing-cpp/core/src/oned/ODCode128Patterns.h \
    $$PWD/../3rd/zxing-cpp/core/src/oned/ODCode128Reader.h \
    $$PWD/../3rd/zxing-cpp/core/src/oned/ODCode128Writer.h \
    $$PWD/../3rd/zxing-cpp/core/src/oned/ODCode39Reader.h \
    $$PWD/../3rd/zxing-cpp/core/src/oned/ODCode39Writer.h \
    $$PWD/../3rd/zxing-cpp/core/src/oned/ODCode93Reader.h \
    $$PWD/../3rd/zxing-cpp/core/src/oned/ODCode93Writer.h \
    $$PWD/../3rd/zxing-cpp/core/src/oned/ODDXFilmEdgeReader.h \
    $$PWD/../3rd/zxing-cpp/core/src/oned/ODDataBarCommon.h \
    $$PWD/../3rd/zxing-cpp/core/src/oned/ODDataBarExpandedBitDecoder.h \
    $$PWD/../3rd/zxing-cpp/core/src/oned/ODDataBarExpandedReader.h \
    $$PWD/../3rd/zxing-cpp/core/src/oned/ODDataBarReader.h \
    $$PWD/../3rd/zxing-cpp/core/src/oned/ODEAN13Writer.h \
    $$PWD/../3rd/zxing-cpp/core/src/oned/ODEAN8Writer.h \
    $$PWD/../3rd/zxing-cpp/core/src/oned/ODITFReader.h \
    $$PWD/../3rd/zxing-cpp/core/src/oned/ODITFWriter.h \
    $$PWD/../3rd/zxing-cpp/core/src/oned/ODMultiUPCEANReader.h \
    $$PWD/../3rd/zxing-cpp/core/src/oned/ODReader.h \
    $$PWD/../3rd/zxing-cpp/core/src/oned/ODRowReader.h \
    $$PWD/../3rd/zxing-cpp/core/src/oned/ODUPCAWriter.h \
    $$PWD/../3rd/zxing-cpp/core/src/oned/ODUPCEANCommon.h \
    $$PWD/../3rd/zxing-cpp/core/src/oned/ODUPCEWriter.h \
    $$PWD/../3rd/zxing-cpp/core/src/oned/ODWriterHelper.h \
    $$PWD/../3rd/zxing-cpp/core/src/pdf417/CustomData.h \
    $$PWD/../3rd/zxing-cpp/core/src/pdf417/PDFBarcodeMetadata.h \
    $$PWD/../3rd/zxing-cpp/core/src/pdf417/PDFBarcodeValue.h \
    $$PWD/../3rd/zxing-cpp/core/src/pdf417/PDFBoundingBox.h \
    $$PWD/../3rd/zxing-cpp/core/src/pdf417/PDFCodeword.h \
    $$PWD/../3rd/zxing-cpp/core/src/pdf417/PDFCodewordDecoder.h \
    $$PWD/../3rd/zxing-cpp/core/src/pdf417/PDFCompaction.h \
    $$PWD/../3rd/zxing-cpp/core/src/pdf417/PDFDecoder.h \
    $$PWD/../3rd/zxing-cpp/core/src/pdf417/PDFDecoderResultExtra.h \
    $$PWD/../3rd/zxing-cpp/core/src/pdf417/PDFDetectionResult.h \
    $$PWD/../3rd/zxing-cpp/core/src/pdf417/PDFDetectionResultColumn.h \
    $$PWD/../3rd/zxing-cpp/core/src/pdf417/PDFDetector.h \
    $$PWD/../3rd/zxing-cpp/core/src/pdf417/PDFEncoder.h \
    $$PWD/../3rd/zxing-cpp/core/src/pdf417/PDFHighLevelEncoder.h \
    $$PWD/../3rd/zxing-cpp/core/src/pdf417/PDFModulusGF.h \
    $$PWD/../3rd/zxing-cpp/core/src/pdf417/PDFModulusPoly.h \
    $$PWD/../3rd/zxing-cpp/core/src/pdf417/PDFReader.h \
    $$PWD/../3rd/zxing-cpp/core/src/pdf417/PDFScanningDecoder.h \
    $$PWD/../3rd/zxing-cpp/core/src/pdf417/PDFWriter.h \
    $$PWD/../3rd/zxing-cpp/core/src/pdf417/ZXBigInteger.h \
    $$PWD/../3rd/zxing-cpp/core/src/pdf417/ZXNullable.h

SOURCES += \
    $$PWD/../3rd/zxing-cpp/core/src/Barcode.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/BarcodeFormat.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/BinaryBitmap.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/BitArray.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/BitMatrix.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/BitMatrixIO.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/BitSource.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/CharacterSet.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/ConcentricFinder.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/Content.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/DecodeHints.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/ECI.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/Error.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/GTIN.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/GenericGF.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/GenericGFPoly.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/GlobalHistogramBinarizer.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/GridSampler.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/HRI.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/HybridBinarizer.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/MultiFormatReader.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/MultiFormatWriter.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/PerspectiveTransform.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/ReadBarcode.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/ReedSolomonDecoder.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/ReedSolomonEncoder.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/ResultPoint.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/TextDecoder.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/TextEncoder.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/TextUtfEncoding.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/Utf.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/WhiteRectDetector.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/WriteBarcode.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/ZXingC.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/ZXingCpp.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/qrcode/QRBitMatrixParser.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/qrcode/QRCodecMode.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/qrcode/QRDataBlock.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/qrcode/QRDecoder.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/qrcode/QRDetector.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/qrcode/QREncoder.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/qrcode/QRErrorCorrectionLevel.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/qrcode/QRFormatInformation.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/qrcode/QRMaskUtil.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/qrcode/QRMatrixUtil.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/qrcode/QRReader.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/qrcode/QRVersion.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/qrcode/QRWriter.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/aztec/AZDecoder.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/aztec/AZDetector.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/aztec/AZEncoder.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/aztec/AZHighLevelEncoder.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/aztec/AZReader.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/aztec/AZToken.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/aztec/AZWriter.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/datamatrix/DMBitLayout.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/datamatrix/DMDataBlock.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/datamatrix/DMDecoder.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/datamatrix/DMDetector.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/datamatrix/DMECEncoder.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/datamatrix/DMHighLevelEncoder.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/datamatrix/DMReader.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/datamatrix/DMSymbolInfo.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/datamatrix/DMVersion.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/datamatrix/DMWriter.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/libzueci/zueci.c \
    $$PWD/../3rd/zxing-cpp/core/src/maxicode/MCBitMatrixParser.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/maxicode/MCDecoder.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/maxicode/MCReader.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/oned/ODCodabarReader.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/oned/ODCodabarWriter.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/oned/ODCode128Patterns.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/oned/ODCode128Reader.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/oned/ODCode128Writer.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/oned/ODCode39Reader.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/oned/ODCode39Writer.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/oned/ODCode93Reader.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/oned/ODCode93Writer.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/oned/ODDXFilmEdgeReader.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/oned/ODDataBarCommon.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/oned/ODDataBarExpandedBitDecoder.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/oned/ODDataBarExpandedReader.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/oned/ODDataBarReader.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/oned/ODEAN13Writer.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/oned/ODEAN8Writer.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/oned/ODITFReader.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/oned/ODITFWriter.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/oned/ODMultiUPCEANReader.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/oned/ODReader.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/oned/ODUPCAWriter.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/oned/ODUPCEANCommon.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/oned/ODUPCEWriter.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/oned/ODWriterHelper.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/pdf417/PDFBarcodeValue.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/pdf417/PDFBoundingBox.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/pdf417/PDFCodewordDecoder.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/pdf417/PDFDecoder.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/pdf417/PDFDetectionResult.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/pdf417/PDFDetectionResultColumn.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/pdf417/PDFDetector.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/pdf417/PDFEncoder.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/pdf417/PDFHighLevelEncoder.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/pdf417/PDFModulusGF.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/pdf417/PDFModulusPoly.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/pdf417/PDFReader.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/pdf417/PDFScanningDecoder.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/pdf417/PDFWriter.cpp \
    $$PWD/../3rd/zxing-cpp/core/src/pdf417/ZXBigInteger.cpp


INCLUDEPATH += $$PWD/../3rd/zxing-cpp/core/src
